pipeline {
    agent {
        docker {
        image '51.250.103.143:8132/builder:1.0'
        args '-v /var/run/docker.sock:/var/run/docker.sock -u root'
        }
    }
    
    stages {
        stage('Git') {
            steps {
                git 'https://github.com/eugenerest/boxfuse.git'
            }
        }
        
        stage('Build') {
            steps {
                sh 'mvn package'
            }
        }
        
        stage('Create docker image') {
            steps {
                sh 'docker build -t mywebapp:1.0 .'
                sh 'docker tag builder:1.0 51.250.103.143:8132/mywebapp:1.0 && docker push 51.250.103.143:8132/mywebapp:1.0'
            }
        }
        stage('App on prod') {
            agent{
                label 'node1'
            }
            steps {
                sh 'docker run -d --name boxfuse -p 8081:8080 51.250.103.143:8132/mywebapp:1.0'
            }
        }
    }
} 