pipeline {
    agent {
        label 'docker'
        image '178.154.193.170:8132/builder:1.0'
        args '-v /var/run/docker.sock:/var/run/docker.sock -u root'
    }
    
    stages {
        stage('Git') {
            steps {
                git 'https://github.com/eugenerest/boxfuse.git'
            }
        }
        
        stage('Build') {
            steps {
                sh 'mvn package'
            }
        }
        
        stage('Create docker image') {
            steps {
                sh 'docker build -t mywebapp:1.0 .'
                sh 'docker tag builder:1.0 178.154.193.170:8132/mywebapp:1.0 && docker push 178.154.193.170:8132/mywebapp:1.0'
            }
        }
        stage('App on prod') {
            agent{
                label 'node1'
            }
            steps {
                sh 'docker run -d --name boxfuse -p 8081:8080 178.154.193.170:8132/mywebapp:1.0'
            }
        }
    }
}