version: "3.2"
services:
  packer:
    build: .
    volumes:
     - type: volume
       source: artefact
       target: /tmp/boxfuse-sample-java-war-hello/target/

  production:
    image: tomcat:9.0.20-jre8-alpine
    depends_on:
      - packer
    volumes:
     - type: volume
       source: artefact
       target: /usr/local/tomcat/webapps/
    ports:
      - "8080:8080"
    entrypoint:
      - "catalina.sh"
      - "run"