---
# tasks file for packer
- name: Ensure packages is present
  apt: name={{item}} state=present
  with_items:
       - default-jdk
       - git
       - maven

- name: Clone a github repository
  repo: {{ git_repo }}
  dest: {{ local_repo }}
  clone: yes
  update: yes

- name: Ensure boxfuse is packaged
  command: mvn -f /home/restes/boxfuse/pom.xml package