---
- name: Preparation and packaging
  hosts: packer
  become: yes

  tasks:
  - name: Ensure default-jdk is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure git is present
    apt:
      name: git
      state: present

  - name: Ensure maven is present
    apt:
      name: maven
      state: present

  - name: Clone a github repository
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
      dest: /home/restes/boxfuse/
      clone: yes
      update: yes

  - name: Ensure boxfuse is packaged
    command: mvn -f /home/restes/boxfuse/pom.xml package

- name: Production
  hosts: prod
  become: yes

  tasks:
  - name: Ensure tomcat is present
    apt:
      name: tomcat9
      state: present

  - name: Copy Maven artifact from Packer to Prod
    synchronize: src=/home/restes/boxfuse/target/hello-1.0.war dest=/var/lib/tomcat9/webapps
    delegate_to: 84.201.164.170